/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlinkPriceOracleSol from "./ChainlinkPriceOracle.sol";
export type { chainlinkPriceOracleSol };
export type { SignedPriceOracle } from "./SignedPriceOracle";
