/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace EthCollateralCrate {
  export type OracleConfigStruct = {
    priceOracle: AddressLike;
    priceOracleId: BytesLike;
    ethOracle: AddressLike;
    ethOracleId: BytesLike;
    priceDecimals: BigNumberish;
    ethPriceDecimals: BigNumberish;
  };

  export type OracleConfigStructOutput = [
    priceOracle: string,
    priceOracleId: string,
    ethOracle: string,
    ethOracleId: string,
    priceDecimals: bigint,
    ethPriceDecimals: bigint
  ] & {
    priceOracle: string;
    priceOracleId: string;
    ethOracle: string;
    ethOracleId: string;
    priceDecimals: bigint;
    ethPriceDecimals: bigint;
  };

  export type FeeConfigStruct = {
    mintFeeBps: BigNumberish;
    burnFeeBps: BigNumberish;
    treasury: AddressLike;
  };

  export type FeeConfigStructOutput = [
    mintFeeBps: bigint,
    burnFeeBps: bigint,
    treasury: string
  ] & { mintFeeBps: bigint; burnFeeBps: bigint; treasury: string };
}

export interface CrateFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FACTORY_ADMIN_ROLE"
      | "allCrates"
      | "crateById"
      | "crateCount"
      | "createEthCollateralCrate"
      | "createExposureCrate"
      | "createStrategyCrate"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EthCollateralCrateDeployed"
      | "ExposureCrateDeployed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StrategyCrateDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FACTORY_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allCrates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crateById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEthCollateralCrate",
    values: [
      string,
      string,
      BigNumberish,
      AddressLike,
      EthCollateralCrate.OracleConfigStruct,
      EthCollateralCrate.FeeConfigStruct,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createExposureCrate",
    values: [BigNumberish, AddressLike, AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createStrategyCrate",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FACTORY_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allCrates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "crateById", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "crateCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEthCollateralCrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createExposureCrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStrategyCrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace EthCollateralCrateDeployedEvent {
  export type InputTuple = [
    crate: AddressLike,
    crateId: BigNumberish,
    oracleId: BytesLike,
    ethOracleId: BytesLike
  ];
  export type OutputTuple = [
    crate: string,
    crateId: bigint,
    oracleId: string,
    ethOracleId: string
  ];
  export interface OutputObject {
    crate: string;
    crateId: bigint;
    oracleId: string;
    ethOracleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExposureCrateDeployedEvent {
  export type InputTuple = [
    crate: AddressLike,
    crateId: BigNumberish,
    oracleId: BytesLike
  ];
  export type OutputTuple = [crate: string, crateId: bigint, oracleId: string];
  export interface OutputObject {
    crate: string;
    crateId: bigint;
    oracleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyCrateDeployedEvent {
  export type InputTuple = [crate: AddressLike, crateId: BigNumberish];
  export type OutputTuple = [crate: string, crateId: bigint];
  export interface OutputObject {
    crate: string;
    crateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrateFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CrateFactory;
  waitForDeployment(): Promise<this>;

  interface: CrateFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FACTORY_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  allCrates: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  crateById: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  crateCount: TypedContractMethod<[], [bigint], "view">;

  createEthCollateralCrate: TypedContractMethod<
    [
      name: string,
      symbol: string,
      crateId: BigNumberish,
      rebateController: AddressLike,
      oracleCfg: EthCollateralCrate.OracleConfigStruct,
      feeCfg: EthCollateralCrate.FeeConfigStruct,
      admin: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  createExposureCrate: TypedContractMethod<
    [
      crateId: BigNumberish,
      rebateController: AddressLike,
      oracle: AddressLike,
      oracleId: BytesLike,
      admin: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  createStrategyCrate: TypedContractMethod<
    [crateId: BigNumberish, rebateController: AddressLike, admin: AddressLike],
    [string],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FACTORY_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allCrates"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "crateById"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "crateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createEthCollateralCrate"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      crateId: BigNumberish,
      rebateController: AddressLike,
      oracleCfg: EthCollateralCrate.OracleConfigStruct,
      feeCfg: EthCollateralCrate.FeeConfigStruct,
      admin: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createExposureCrate"
  ): TypedContractMethod<
    [
      crateId: BigNumberish,
      rebateController: AddressLike,
      oracle: AddressLike,
      oracleId: BytesLike,
      admin: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createStrategyCrate"
  ): TypedContractMethod<
    [crateId: BigNumberish, rebateController: AddressLike, admin: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "EthCollateralCrateDeployed"
  ): TypedContractEvent<
    EthCollateralCrateDeployedEvent.InputTuple,
    EthCollateralCrateDeployedEvent.OutputTuple,
    EthCollateralCrateDeployedEvent.OutputObject
  >;
  getEvent(
    key: "ExposureCrateDeployed"
  ): TypedContractEvent<
    ExposureCrateDeployedEvent.InputTuple,
    ExposureCrateDeployedEvent.OutputTuple,
    ExposureCrateDeployedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyCrateDeployed"
  ): TypedContractEvent<
    StrategyCrateDeployedEvent.InputTuple,
    StrategyCrateDeployedEvent.OutputTuple,
    StrategyCrateDeployedEvent.OutputObject
  >;

  filters: {
    "EthCollateralCrateDeployed(address,uint256,bytes32,bytes32)": TypedContractEvent<
      EthCollateralCrateDeployedEvent.InputTuple,
      EthCollateralCrateDeployedEvent.OutputTuple,
      EthCollateralCrateDeployedEvent.OutputObject
    >;
    EthCollateralCrateDeployed: TypedContractEvent<
      EthCollateralCrateDeployedEvent.InputTuple,
      EthCollateralCrateDeployedEvent.OutputTuple,
      EthCollateralCrateDeployedEvent.OutputObject
    >;

    "ExposureCrateDeployed(address,uint256,bytes32)": TypedContractEvent<
      ExposureCrateDeployedEvent.InputTuple,
      ExposureCrateDeployedEvent.OutputTuple,
      ExposureCrateDeployedEvent.OutputObject
    >;
    ExposureCrateDeployed: TypedContractEvent<
      ExposureCrateDeployedEvent.InputTuple,
      ExposureCrateDeployedEvent.OutputTuple,
      ExposureCrateDeployedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StrategyCrateDeployed(address,uint256)": TypedContractEvent<
      StrategyCrateDeployedEvent.InputTuple,
      StrategyCrateDeployedEvent.OutputTuple,
      StrategyCrateDeployedEvent.OutputObject
    >;
    StrategyCrateDeployed: TypedContractEvent<
      StrategyCrateDeployedEvent.InputTuple,
      StrategyCrateDeployedEvent.OutputTuple,
      StrategyCrateDeployedEvent.OutputObject
    >;
  };
}
